#!/usr/bin/env python3
"""Sort raw producer pickles into a tagged unfolder input set.

The producer (smp_jetmass_run2) writes pickles named like

    <mode>_<sample>_<era>.pkl          # zjet, e.g. minimal_rho_pythia_2017.pkl
    <mode>_<channel>_<sample>_<era>.pkl # dijet/trijet (channel prefix)

while the unfolder expects a per-tag directory ``inputs/<channel>/<observable>/<tag>/``
holding files in *its* convention:

    pythia_<era>.pkl  jk_pythia_<era>.pkl  pythia_all.pkl
    data_all.pkl      jk_data_all.pkl      herwig_all.pkl

This script takes a folder of raw producer pickles, asks for (or accepts) a
tag, renames each file into the unfolder convention, and drops it into the tag
directory. Any required file the raw drop does not provide is back-filled from a
base tag (default: ``original``) via a relative symlink, so a partial drop --
e.g. only the four ``pythia_<era>`` files -- yields a complete, runnable tag
that reuses the unchanged data/herwig/jackknife inputs.

Examples
--------
    # interactive: prompts for the tag
    python scripts/organize_inputs.py --raw rawInputs

    # non-interactive, rename a pythia-only drop already sitting in the tag dir
    python scripts/organize_inputs.py \
        --raw inputs/zjet/rho/fixed_miss --tag fixed_miss --base-tag original

After it runs, register the tag in unfolder_core (see the printed snippet) and
run:  python scripts/run_unfolding.py --channel zjet --observable rho --tag <tag>
"""
from __future__ import annotations

import argparse
import os
import shutil
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]

# Era tokens the producer uses as the trailing <era> field.
KNOWN_ERAS = ("2016APV", "2016", "2017", "2018", "all")
# Sample tokens the producer uses for the <sample> field.
KNOWN_SAMPLES = ("pythia", "data", "herwig", "madgraph", "st", "singletop")

# Files the zjet unfolder needs for a full systematic run, in *its* convention.
# pythia_all.pkl is regenerated by Unfolder._merge_eras, so it is not required
# to pre-exist; everything else must be present (either from the raw drop or
# back-filled from the base tag).
REQUIRED_FILES = (
    "pythia_2016.pkl",
    "pythia_2016APV.pkl",
    "pythia_2017.pkl",
    "pythia_2018.pkl",
    "jk_pythia_2016.pkl",
    "jk_pythia_2016APV.pkl",
    "jk_pythia_2017.pkl",
    "jk_pythia_2018.pkl",
    "data_all.pkl",
    "jk_data_all.pkl",
    "herwig_all.pkl",
)
# Optional read-only extras worth back-filling when present in the base tag.
# NOTE: pythia_all.pkl is deliberately NOT here. Unfolder._merge_eras opens it
# with "wb"; a symlink would be followed and clobber the base tag's file. The
# unfolder regenerates a fresh real pythia_all.pkl from the per-era pickles.
OPTIONAL_FILES = ("pythia_reweighted_all.pkl",)


def unfolder_name(raw_stem: str) -> str | None:
    """Map a raw producer stem to the unfolder filename, or None if unparseable.

    Strips the leading mode/channel tokens and keeps ``[jk_]<sample>_<era>``.
    Data is only ever consumed merged, so ``data_<era>`` collapses to
    ``data_all`` only when era == 'all'; per-era data is passed through as-is
    (the unfolder does not merge data eras itself).
    """
    tokens = raw_stem.split("_")
    if len(tokens) < 2:
        return None

    era = tokens[-1]
    if era not in KNOWN_ERAS:
        return None

    is_jk = "jk" in tokens
    sample = next((t for t in tokens if t in KNOWN_SAMPLES), None)
    if sample is None:
        return None

    prefix = "jk_" if is_jk else ""
    return f"{prefix}{sample}_{era}.pkl"


def place(src: Path, dst: Path, *, copy: bool, dry_run: bool) -> None:
    if dst.exists() or dst.is_symlink():
        dst.unlink() if not dry_run else None
    if dry_run:
        return
    if copy:
        shutil.copy2(src, dst)
    else:
        # Relative symlink so the tree stays portable when moved.
        os.symlink(os.path.relpath(src.resolve(), dst.parent), dst)


def main() -> None:
    parser = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    parser.add_argument(
        "--raw", type=Path, default=REPO_ROOT / "rawInputs",
        help="Folder of raw producer pickles (default: ./rawInputs).",
    )
    parser.add_argument("--tag", default=None, help="Tag name (prompted if omitted).")
    parser.add_argument("--channel", default="zjet")
    parser.add_argument("--observable", default="rho")
    parser.add_argument(
        "--base-tag", default="original",
        help="Tag to back-fill missing required files from (default: original).",
    )
    parser.add_argument(
        "--copy", action="store_true",
        help="Copy back-filled files instead of symlinking them.",
    )
    parser.add_argument("--dry-run", action="store_true")
    args = parser.parse_args()

    if not args.raw.is_dir():
        sys.exit(f"Raw folder not found: {args.raw}")

    tag = args.tag or input("Tag for this input set (e.g. fixed_miss): ").strip()
    if not tag:
        sys.exit("No tag given.")

    inputs_root = REPO_ROOT / "inputs" / args.channel / args.observable
    tag_dir = inputs_root / tag
    base_dir = inputs_root / args.base_tag
    in_place = args.raw.resolve() == tag_dir.resolve()

    if not args.dry_run:
        tag_dir.mkdir(parents=True, exist_ok=True)

    print(f"Raw     : {args.raw}")
    print(f"Tag dir : {tag_dir}")
    print(f"Base tag: {base_dir}  ({'copy' if args.copy else 'symlink'} for missing)")
    print(f"In-place: {in_place}\n")

    # 1) Map + place every raw pickle.
    placed: dict[str, str] = {}
    skipped: list[str] = []
    for src in sorted(args.raw.glob("*.pkl")):
        mapped = unfolder_name(src.stem)
        if mapped is None:
            skipped.append(src.name)
            continue
        dst = tag_dir / mapped
        if in_place and src.name != mapped:
            # Rename the raw file in place (always a real move, never a link).
            if not args.dry_run:
                if dst.exists() or dst.is_symlink():
                    dst.unlink()
                src.rename(dst)
        elif not in_place:
            place(src, dst, copy=True, dry_run=args.dry_run)  # always copy real data in
        placed[mapped] = src.name
        print(f"  {src.name:42s} -> {mapped}")

    if skipped:
        print("\n  [skipped, unrecognized]:", ", ".join(skipped))

    # 2) Back-fill required (and optional, if present) files from the base tag.
    print("\nBack-filling from base tag:")
    missing_base: list[str] = []
    for name in REQUIRED_FILES + OPTIONAL_FILES:
        if name in placed or (tag_dir / name).exists():
            continue
        base_file = base_dir / name
        if not base_file.exists():
            if name in REQUIRED_FILES:
                missing_base.append(name)
            continue
        place(base_file, tag_dir / name, copy=args.copy, dry_run=args.dry_run)
        print(f"  {name:42s} <- {args.base_tag}/")

    # 3) Verify completeness.
    print("\nCompleteness check:")
    still_missing = [
        n for n in REQUIRED_FILES
        if not args.dry_run and not (tag_dir / n).exists()
    ]
    if still_missing:
        print("  MISSING required files:", ", ".join(still_missing))
        if missing_base:
            print(f"  (not found in base tag '{args.base_tag}': {', '.join(missing_base)})")
    else:
        print("  OK -- all required files present"
              + (" (dry-run, not verified on disk)" if args.dry_run else ""))

    # 4) Tell the user how to wire it into the runner.
    inp = f"./inputs/{args.channel}/{args.observable}/{tag}/"
    out = f"outputs/{args.channel}/{args.observable}/{tag}/"
    print(
        "\nNext steps\n"
        "----------\n"
        "1) Register the tag in src/unfold/tools/unfolder_core.py (near RHO_SPECS):\n\n"
        f'    RHO_{tag.upper()}_SPEC = replace(\n'
        f'        RHO_FIXED_JEC_SPEC,\n'
        f'        input_dir="{inp}",\n'
        f'        output_dir="{out}",\n'
        f'    )\n'
        f'    RHO_SPECS["{tag}"] = RHO_{tag.upper()}_SPEC\n'
        f'    ZJET_SPECS[("{args.observable}", "{tag}")] = RHO_{tag.upper()}_SPEC\n\n'
        "2) Run:\n"
        f"    source scripts/setup_root.sh\n"
        f"    python scripts/run_unfolding.py --channel {args.channel} "
        f"--observable {args.observable} --tag {tag}\n"
    )


if __name__ == "__main__":
    main()
